"""add language to posts again

Revision ID: d5acb53f16e6
Revises: 421d75057a8a
Create Date: 2018-06-12 22:09:47.515173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5acb53f16e6'
down_revision = '421d75057a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
